### ISSUE TITLE
well made, but old.... 27 commits ago heh

### ISSUE THREAD

**Issue by PunCakeCat** [maywr/Firework#4]

**Comment by master7720** [comment]
all readme or mc.info commits

**Comment by maywr** [comment]
слышишь хуйня хохлянская соси мой хуек

**Comment by master7720** [comment]
> слышишь хуйня хохлянская соси мой хуек


?english pls

**Comment by maywr** [comment]
> > слышишь хуйня хохлянская соси мой хуек
> 
> 
> ?english pls

goggle translate

**Comment by PunCakeCat** [comment]
> all readme or mc.info commits
idk what about u, but we don't call them commits
maybe for your paste client it is routine

**Comment by kisman2000** [comment]
уебись об стену, возьми пример с дазеда и не пиши читы для кубов вообще

**Comment by master7720** [comment]
> > all readme or mc.info commits
> 
> idk what about u, but we don't call them commits maybe for your paste client it is routine

Lynx isnt a skid LOL
